# docker build -t fschlatt/authorship-verification-trivial:0.0.1 .
FROM fschlatt/natural-language-processing-exercises:0.0.1

ADD some_idea.py /code/some_idea.py

ENTRYPOINT [ "python3", "/code/some_idea.py" ]
